language: ruby
rvm:
  - 1.8.7
#  - 1.9.3
script: 'rake spec'
before_install:
    - sudo add-apt-repository -y ppa:raphink/augeas
    - sudo apt-get update -qq
    - sudo apt-get install -qq libaugeas0 libaugeas-dev
    - sudo rm -f /usr/share/augeas/lenses/dist/splunk.aug
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="3.3"
gemfile: .gemfile
notifications:
  email: false
